remote_theme: "mmistakes/minimal-mistakes@4.16.6"
title: Priyanka Raina
description: Priyanka Raina's personal website
plugins:
  - jekyll-include-cache
sidebar:
  - title: "Title"
    image: http://placehold.it/350x250
    image_alt: "image"
    text: "Some text here."
  - title: "Another Title"
    text: "More text here."
