remote_theme: "mmistakes/minimal-mistakes@4.16.6"
title: Priyanka Raina
description: Priyanka Raina's personal website
plugins:
  - jekyll-include-cache
author_profile: true
include: ["_pages"]
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"
